---
go:
  - 1.12
python:
  - 2.7

services: docker

env:
  - distro: ubuntu1204
  - distro: ubuntu1210
  - distro: ubuntu1304
  - distro: ubuntu1310
  - distro: ubuntu1404
  - distro: ubuntu1410
  - distro: ubuntu1504
  - distro: ubuntu1510
  - distro: ubuntu1604
  - distro: ubuntu1610
  - distro: ubuntu1704
  - distro: ubuntu1710
  - distro: ubuntu1804
  - distro: ubuntu1810
  - distro: ubuntu1904
  - distro: centos6
  - distro: centos7
  - distro: debian8
  - distro: debian9
  - distro: debian10
  - distro: fedora24
  - distro: fedora25
  - distro: fedora26
  - distro: fedora27
  - distro: fedora28
  - distro: fedora29
  - distro: fedora30
  - distro: fedora31

before_install:
  - sudo pip install --upgrade pip
  - sudo pip install ansible
  - sudo pip install ansible-lint
  - ansible-lint . || true
  - go get -v github.com/fubarhouse/ansible-role-tester

script:
  - ansible-role-tester full --distribution ${distro}

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
