---
go:
  - 1.10
python:
  - 2.7

services: docker

env:
  - distro: precise
  - distro: quantal
  - distro: raring
  - distro: saucy
  - distro: trusty
  - distro: utopic
  - distro: vivid
  - distro: wily
  - distro: xenial
  - distro: yakkety
  - distro: zesty
  - distro: artful
  - distro: bionic
  - distro: cosmic
  - distro: centos-6
  - distro: centos-7
  - distro: wheezy
  - distro: jessie
  - distro: stretch
  - distro: buster
  - distro: fedora-24
  - distro: fedora-25
  - distro: fedora-26
  - distro: fedora-27
  - distro: fedora-28
  - distro: fedora-29

before_install:
  - sudo pip install --upgrade pip
  - sudo pip install ansible
  - go get -v github.com/fubarhouse/ansible-role-tester

script:
  - ansible-role-tester full --distribution ${distro}

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
