---

- name: "Yarn | De-configure shell profiles"
  lineinfile:
    dest: "{{ fubarhouse_user_dir }}/{{ item }}"
    regexp: "PATH:{{ yarn_global_path }}/bin"
    line:  'export PATH="$PATH:{{ yarn_global_path }}/bin";'
    state: present
  failed_when: false
  with_items:
    - "{{ yarn_shell_profiles }}"
  when: yarn_clean_install

- name: "Yarn | Uninstall"
  package:
    name: yarn
    state: absent
  when:
    - yarn_clean_install

- name: "Yarn | Check for installation"
  command: which yarn
  register: yarn_result
  changed_when: false
  failed_when: false

- name: "Yarn | Register existing installation status"
  set_fact:
    yarn_install_state: true
  changed_when: false
  when: '"yarn" in yarn_result.stdout or yarn_result.rc != 0'

- name: "Yarn | Register existing installation status (true)"
  set_fact:
    yarn_install_state: false
  changed_when: false
  when:
    - 'yarn_result.rc == 0'
    - '"Usage" not in yarn_result.stdout'
    - '"Yarn requires Node" not in yarn_result.stdout'
    - '"is not supported, please use Node.js" not in yarn_result.stdout'

- name: "Yarn | Include OS-specific tasks"
  include_tasks: "yarn-{{ ansible_os_family }}.yml"
  when: yarn_install_state

- name: "Yarn | Install"
  package:
    name: yarn
    state: present
  when: yarn_install_state
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: "Yarn | Configure shell profiles"
  lineinfile:
    dest: "{{ fubarhouse_user_dir }}/{{ item }}"
    regexp: "PATH:{{ yarn_global_path }}/bin"
    line:  'export PATH="$PATH:{{ yarn_global_path }}/bin";'
    state: present
  failed_when: false
  with_items:
    - "{{ yarn_shell_profiles }}"
  when: yarn_install_state

- name: "Yarn | Ensure installed"
  command: "which yarn"
  when: yarn_install_state

- name: "Yarn | Update as required"
  command: "yarn self-update {{ yarn_version | default() }}"
  when: yarn_update
  changed_when: false
  failed_when: false
